langs.fr = { // Property here should match this language name
	"phrases": {
		dark:											"Sombre",
		fullscreen:								"Plein écran",
		fast:											"Rapide",
		steps:										"Pas",
		mute:											"Muet",
		compact:									"Compact",
		reset:										"Réinitialiser",
		alone:										"Seul",
		all:											"Tous",
		title:										"Phasmophobia Ghost Finder",
		line1:										"Sélectionnez des indices ou tapez les numéros pour basculer entre les choix afin de trouver le type de fantôme.",
		line2:										"Utilisez [ et ] pour les cartes : Espace pour sélectionner ; Entrée pour ouvrir la carte. +/- pour changer la difficulté",
		line3:										"Cartes volées sans pitié à",
		gameplay:									"Jeu et informations sur les objets",
		github:										"GitHub",
		discord:									"Discord",
		support_me:								"Soutenez-moi",
		hunt_timers:							"Les minuteries de chasse incluent les différents délais de grâce",
		no_info:									"Aucune information pour l'instant",
		open_map:									"Ouvrir la carte",

		// Minuteries
		timer_start:							"Démarrer",
		timer_hunt:								"Chasse",
		timer_cursed:							"Chasse maudite",
		timer_post_hunt:					"Après la chasse",
		timer_smudge:							"Test Encens classique",
		timer_smudge_spirit:			"Test Encens d'esprit",
		timer_smudge_demon:				"Test Encens de démon",

		// Cartes
		map_bleasdale:						"Bleasdale",
		map_brownstone:						"High School",
		map_edgefield:						"Edgefield",
		map_grafton:							"Grafton",
		map_maple:								"Maple Lodge",
		map_prison:								"Prison",
		map_ridgeview:						"Ridgeview",
		map_sunny:								"Sunny Meadows",
		map_tanglewood:						"Tanglewood",
		map_willow:								"Willow",
		map_woodwind:							"Woodwind",

		// Difficultés
		diff_ama:									"Amateur",
		diff_int:									"Intermédiaire",
		diff_pro:									"Professionnel",
		diff_har:									"Cauchemar",
		diff_san:									"Démence",

		// Onglet photos
		photos:										"Photos",
		type:											"Type",
		stars:										"Étoiles (plus/moins)",
		photo_none:								"--------",
		photo_bone:								"Os",
		photo_cursed_item:				"Objet maudit",
		photo_dead_body:					"Cadavre",
		photo_dots_ghost:					"Fantôme DOTS",
		photo_dirty_water:				"Eau sale",
		photo_finger_prints:			"Empreintes digitales",
		photo_footsteps:					"Empreintes de pas",
		photo_ghost:							"Fantôme",
		photo_ghost_writing:			"Écritures fantômatique",
		photo_interaction:				"Interaction",
		photo_stepped_salt:				"Sel piétiné",
		photo_used_crucifix:			"Crucifix utilisé",
		roll:											"Lancer",

		roll_cat_maps :						"Cartes",
		roll_cat_items :					"Objets",
		roll_cat_clear :					"Effacer",
		roll_cat_all :						"Tous",
		roll_cat_small :					"Petit",
		roll_cat_medium :					"Moyen",
		roll_cat_large :					"Grand",
		roll_cat_evidence :				"Preuves",
		roll_cat_secondary :			"Secondaire",
		roll_cat_lights :					"Lumières",
		roll_cat_electric :				"Électrique",

		// Rolls tab
		roll_bleasdale:						"Bleasdale Farmhouse",
		roll_brownstone:					"Brownstone High School",
		roll_edgefield:						"Edgefield Street",
		roll_grafton:							"Grafton Farmhouse",
		roll_maple:								"Maple Lodge Campsite",
		roll_prison:							"Prison",
		roll_ridgeview:						"10 Ridgeview Court",
		roll_sunny:								"Sunny Meadows",
		roll_tanglewood:					"6 Tanglewood Drive",
		roll_willow:							"13 Willow Street",
		roll_woodwind:						"Camp Woodwind",
		roll_can:									"Bougie",
		roll_cru:									"Crucifix",
		roll_dot:									"Projecteur DOTS",
		roll_emf:									"Lecteur EMF",
		roll_fla:									"Lampe torche",
		roll_gwb:									"Livre d'écriture fantomatique",
		roll_glo:									"Bâton lumineux UV",
		roll_lig:									"Briquet",
		roll_mos:									"Détecteur de mouvement",
		roll_par:									"Microphone parabolique",
		roll_cam:									"Appareil photo",
		roll_sal:									"Sel",
		roll_san:									"Pilules de santé mentale",
		roll_sms:									"Bâton d'encens",
		roll_snd:									"Détecteur sonore",
		roll_spb:									"Spirit box",
		roll_sfl:									"Lampe torche puissante",
		roll_thm:									"Thermomètre",
		roll_tri:									"Trépied",
		roll_uvl:									"Lampe UV",
		roll_vid:									"Caméra vidéo",

		// Indices
		clue_dots: 								"DOTS",
		clue_emf: 								"EMF 5",
		clue_prints: 							"Empreintes dig.",
		clue_temps: 							"Temp. glaciales",
		clue_orb: 								"Orbes",
		clue_writing: 						"Ecritures fant.",
		clue_box:									"Spirit Box",

		// Ghost useful info
		ghost_banshee:						"Banshee",
		ghost_banshee_useful: [
			"Les chasses sont basées sur la santé mentale de la cible ; elle ne chassera que sa cible à moins que cette dernière ne soit à l'extérieur",
			"Elle a tendance à errer autour de sa cible",
			"Préfère chanter lors des événements fantomatiques ; cela draine 15% de la santé mentale",
			"Peut pousser des cris stridents par le biais du microphone parabolique",
			],
		ghost_demon:							"Démon",
		ghost_demon_useful: [
			"Les crucifix ont une portée accrue: 5m",
			//"Peut se téléporter sa cible au début de la chasse, s'il a eu une ligne de mire sur le fantôme dans les 20 dernières secondes", // Potentiellement supprimé
			"Peut chasser à 70% de santé mentale",
			"Faible chance de chasser à n'importe quel niveau de santé mentale",
			"Le délai entre les chasses est réduit à 20s",
			"Les batons d'encens durent 2/3 moins longtemps: 60s",
		],
		ghost_deogen:							"Deogen",
		ghost_deogen_useful: [
			"Peut détecter la position des joueurs pendant la chasse ; les joueurs ne peuvent pas se cacher",
			"Choisit le joueur le plus proche au début de la chasse ; change aléatoirement pour les joueurs plus proches",
			"Se déplace à vitesse maximale (3M/s) au-delà d'une distance de 6m du joueur, ralentissant à 0,4M/s dans les 2,5M",
			"Peut chasser à 40% de santé mentale",
			"Plus de chance d'obtenir des points de preuve DOTS et d'écriture fantômatique",
			"33% de chance d'entendre un son unique de la spirit box (respiration). Doit être à moins de 1m du fantôme",
			"Mode cauchemar : la spirit box est garantie",
			"Lorsqu'il est sous l'effet de l'encens, le fantôme conserve sa vitesse actuelle, sauf s'il se déplace à plus de 3m/s, auquel cas il ralentit à la vitesse de base du joueur pour la durée de la purification.",
			"visible plus longtemps pendant les chasses",
		],
		ghost_goryo:							"Goryo",
		ghost_goryo_useful:				[
			"Ne montre pas les DOTS lorsque des personnes se trouvent dans la pièce du fantôme",
			"Les DOTS ne peuvent être observés qu'à travers une caméra",
			"Ne peut pas changer de pièce favorite ou errer sur de longues distances",
			"Mode cauchemar : les DOTS sont garantis",
		],
		ghost_hantu:							"Hantu",
		ghost_hantu_useful: [
			"2 fois plus susceptible de couper le courant",
			"Ne peut pas réactiver le courant",
			"La vitesse ne s'accélère jamais pendant la chasse ; se déplace plus lentement dans les pièces chaudes, plus vite dans les pièces froides",
			"Se déplace légèrement plus lentement que la vitesse du joueur à 15°C ; la vitesse augmente toutes les -3°C (37,4°F) jusqu'à 1,7 fois la vitesse du joueur à 0°C",
			"Peut expirer de la vapeur pendant les chasses dans les pièces en dessous de 3°C (37,4°F), ou partout si le courant est coupé",
			"Mode Cauchemar : la température glaciale est garanti",
			],
		ghost_jinn:								"Jinn",
		ghost_jinn_useful:				[
			"Ne coupera jamais l'électricité",
			"Avec l'électricité allumée, il y a une chance de faire baisser la santé mentale de 25% dans un rayon de 3 mètres ou dans la même pièce ; déclenche le détecteur EMF au disjoncteur lorsque l'électricité est allumée",
			"Pendant la chasse avec l'électricité allumée, il se déplace à 1,5 fois la vitesse du joueur (2,5 m/s) lorsqu'il poursuit une cible, jusqu'à être à 2 mètres de sa cible",
		],
		ghost_mare:								"Cauchemar",
		ghost_mare_useful:				[
			"Ne peut pas allumer les interrupteurs",
			"Préfère éteindre les lumières lors des interactions",
			"Peut éteindre instantanément les interrupteurs qui sont allumés",
			"Préfère faire exploser les lumières lors des événements fantomatiques",
			"Tentera de fuir les pièces éclairées en errant longuement",
			"Les lumières allumées réduisent le seuil de chasse à 40%",
			"Les lumières éteintes augmentent le seuil de chasse à 60%",
		],
		ghost_mimic:							"Mimic",
		ghost_mimic_useful:				[
			"Peut se comporter comme n'importe quel autre fantôme, y compris les comportements de chasse et les interactions",
			"Changera de comportement toutes les 30 à 120 secondes",
			"Affiche de fausses orbes fantômatiques",
			"Lorsqu'il imite le Thayé, il choisit un âge de départ aléatoire ; changera de fantôme lorsqu'un stade de vieillissement se produira",
		],
		ghost_moroi:							"Moroi",
		ghost_moroi_useful:				[
			"Maudit l'utilisateur de la Spirit Box; la santé mentale diminue tant qu'il est à l'intérieur jusqu'à ce que des pilules soient prises",
			"Maudit également les utilisateurs de microphones parabolique à l'écoute de bruits de pas ou de murmures",
			"Le taux de perte de santé mentale des joueurs maudits est doublé",
			"La vitesse de chasse de base est plus rapide à des taux de santé mentale moyens plus faibles; 90% de la vitesse des joueurs à 50% de santé mentale, 115% à 25% de santé mentale, 135% à 0% de santé mentale",
			"La période de grâce pour l'utilisation de bâtons d'encens dure 2x plus longtemps (12s)",
			"Mode cauchemar : la boîte à esprit est garantie",
		],
		ghost_myling:							"Myling",
		ghost_myling_useful:			[
			"Parle plus souvent au microphone parabolique",
			"Le volume des bruits de chasse et des pas diminue rapidement avec la distance, devenant silencieux à 12m; l'équipement peut dysfonctionner avant que les pas ne soient entendus",
		],
		ghost_obake:							"Obake",
		ghost_obake_useful:				[
			"75% de chance de laisser des empreintes digitales",
			"25% de chance que les empreintes digitales aient 6 doigts",
			"Les empreintes digitales peuvent disparaître après 50% du temps normal",
			"Pendant une chasse, a 6,66% de chances à chaque fois qu'il clignote de se transformer en un modèle de fantôme différent, puis de revenir à sa forme d'origine. Garanti de se produire au moins une fois par chasse",
			"Mode cauchemar : les empreintes digitales sont garanties",
		],
		ghost_oni:								"Oni",
		ghost_oni_useful:					[
			"l'un des types de fantômes les plus actifs",
			"ne fera pas l'événements fantômatique de boule de brume (gémissement unique)",
			"préfère la forme physique pour les événements fantômatiques",
			"la santé mentale baisse deux fois plus à chaque collision des joueurs avec le fantôme",
			"visible plus longtemps pendant les chasses",
		],
		ghost_onryo:							"Onryo",
		ghost_onryo_useful:				[
			"Les bougies agissent comme des crucifix avec une portée de blocage de chasse de 4 mètres. Elles ont la priorité sur le crucifix.",
			"Chassera à chaque troisième flamme éteinte, à moins qu'elle ne soit bloquée par une autre bougie allumée.",
			"Peut chasser à partir de 60% de la santé mentale même sans flamme dans la pièce.",
		],
		ghost_phantom:						"Fantôme",
		ghost_phantom_useful:			[
			"Disparaît mais reste visible sur les photos quand il ne chasse pas",
			"La photo de fantôme ne montre aucun fantôme et n'a pas de brouillage sur la photo",
			"La jauge de santé mentale baisse deux fois plus vite quand le fantôme est visible (s'arrête si caché grâce à une photo)",
			"Peut errer jusqu'à un joueur à l'intérieur ; laisse le détecteur EMF à son emplacement initial",
			"Est visible pendant moins longtemps pendant la chasse (caché pendant 1 à 2 secondes)",
		],
		ghost_poltergeist:				"Poltergeist",
		ghost_poltergeist_useful:	[
			"Peut lancer des objets à grande vitesse",
			"Peut lancer plusieurs objets à la fois",
			"Perte de 2% de la santé mentale des témoins pour chaque objet lancé en masse",
			"100% de chances de lancer des objets toutes les 0,5 secondes pendant la chasse",
		],
		ghost_raiju:							"Raiju",
		ghost_raiju_useful:				[
			"Peut chasser à 65% de santé mentale moyenne lorsqu'il est près d'appareils électroniques",
			"Vitesse d'environ 1,5x pendant la chasse lorsqu'il est près d'appareils électroniques",
			"A une portée de perturbation électrique de 1,5x",
		],
		ghost_revenant:						"Revenant",
		ghost_revenant_useful:		[
			"Se déplace très rapidement lorsqu'il peut voir un joueur",
			"Se déplace très lentement lorsqu'il ne voit pas de joueur",
			"Lorsque la ligne de mire est perdue pendant la poursuite, le revenant ne ralentit que lorsqu'il a atteint la dernière position connue du joueur",
			"Après avoir atteint la dernière position connue du joueur, le revenant reprend sa vitesse normale en 2,7 secondes.",
		],
		ghost_shade:							"Ombre",
		ghost_shade_useful:				[
			"Très inactif",
			"Ne lancera rien si quelqu'un est dans la pièce du fantôme",
			"Chance d'événements fantômatique liée à la perte de santé mentale ; chances normales en dessous de 50%",
			"Préfère les événements de souffles fantômatique",
			"Préfère la forme d'ombre lors des événements fantômatiques",
			"Ne peut pas chasser au-dessus de 35% de santé mentale",
			"Ne cherchera pas à chasser s'il y a quelqu'un dans la pièce",
		],
		ghost_spirit:							"Spirit",
		ghost_spirit_useful:			[
			"L'action des bâtons d'encens durent 2x plus longtemps : 180s"
		],
		ghost_thaye:							"Thayé",
		ghost_thaye_useful:				[
			"2x de chance d'interagir et d'exécuter des événements paranormaux",
			"Chance accrue d'avoir des Orbes fantômatiques et des Écritures Fantômatiques",
			"Essaie de vieillir tous les 1-2 minutes; s'il n'y a aucun joueur dans la pièce du fantôme, il réessaye toutes les 30 secondes jusqu'à réussite",
			"Tant que le fantôme est jeune, il peut chasser à 75% de santé mentale; -6% de santé mentale par stade de vieillissement",
			"10 stades de vieillissement; la chance d'interaction et d'événements de paranormaux est réduite de 15% par stade de vieillissement, jusqu'à 50%",
			"Vitesse réduite de 10% de la vitesse du joueur par stade de vieillissement, de 166% de la vitesse du joueur jusqu'à 60%; n'accélère pas pendant les chasses",
			"Quand le fantôme est vieux, il peut chasser à 15% de santé mentale",
			"Quand le fantôme est vieux, il ne cherchera pas à chasser si quelqu'un est dans la pièce",
			"Les changements d'âge sont reflétés dans les réponses du Ouija",
		],
		ghost_twins:							"Les Jumeaux",
		ghost_twins_useful:				[
			"Les deux jumeaux occupent le même emplacement, cependant le leurre a un rayon d'interaction de 16m",
			"Les deux jumeaux peuvent interagir l'un après l'autre",
			"N'importe lequel des jumeaux peut déclencher une chasse ; le jumeau principal se déplace à -10 %, le leurre se déplace à +10 %",
			"Les chasses du leurre commencent immédiatement après une interaction du leurre",
		],
		ghost_wraith:							"Spectre",
		ghost_wraith_useful:			[
			"Ne marchera jamais dans le sel",
			"Peut se téléporter près d'un joueur aléatoire à l'intérieur et laisser de l'EMF sur la position du joueur",
		],
		ghost_yokai:							"Yokai",
		ghost_yokai_useful:				[
			"Activité accrue lorsque les joueurs parlent près du fantôme",
			"Peut chasser en dessous de 80% de sanité lorsque les joueurs parlent à proximité",
			"Ne peut entendre les joueurs et détecter les équipements électroniques à moins de 2,5 mètres de distance que lors des chasses",
		],
		ghost_yurei:							"Yurei",
		ghost_yurei_useful:				[
			"Préfère les interactions avec les portes",
			"Chance de faire baisser la santé mentale de 15% dans un rayon de 3m (ferme une porte proche)",
			"Ne peut pas se déplacer lorsqu'il est sous l'effet de l'encens",
		],

		// Gameplay info
		gameplay_hotkeys:	"Raccourcis clavier",
		gameplay_hotkeys_items: [
			"0-9	Basculer chaque élément de preuve pour confirmer ou rejeter, pour aider à identifier le fantôme. Lorsque l'onglet Photos est sorti, bascule les types de photo individuels",
			"[ / ]	Parcourir les cartes disponibles : appuyer sur Espace pour sélectionner la carte ; Entrée pour ouvrir. Lorsque l'onglet Photos est sorti, permet de sélectionner la qualité des photos",
			"+ / -	Augmenter ou diminuer la difficulté",
			"Q-U	Sélectionner un minuteur et utiliser # pour démarrer ou arrêter. Appuyer à nouveau sur la touche de lettre pour réinitialiser",
			",	Basculer la vitesse de pas du fantôme à 1,5x",
			".	Démarrer ou arrêter le minuteur de pas par défaut, pour le comparer à la vitesse de pas du fantôme",
			"#	Démarrer ou arrêter le minuteur sélectionné",
			"A	Basculer entre le fantôme seul / tous les joueurs fantômes",
			"C	Basculer en mode compact (astuces fantômes masquées)",
			"D	Basculer en mode sombre",
			"F	Basculer en mode plein écran",
			"S	Ouvre l'onglet Photos",
			"L	Ouvre l'onglet Rouleau (journal)",
			"M	Désactiver les sons du minuteur",
			"X	Réinitialiser le chercheur de fantômes pour le prochain fantôme. Ne modifiera pas la carte, la difficulté ou le minuteur sélectionné",
		],
		gameplay_general: 						"Général",
		gameplay_general_items: 			[
			"Se mettre accroupi réduit la zone visible du joueur pour le fantôme et permet de voir le sol dans les zones sombres",
			"Sprinter permet un déplacement à ~1,8x pendant 3,5s avec un temps de récupération de 5s - la durée peut être ajustée",
			"Les os peuvent apparaître dans n'importe quelle zone non-fermée; ils n'apparaissent pas dans les armoires, mais peuvent apparaître dans les encadrements de porte levée, les serviettes et les tapis",
			"Tous les fantômes ont une pièce préférée, mais la «pièce du fantôme» ne fait référence qu'à la pièce où le fantôme se trouve actuellement. Les fantômes de difficulté Professionnel et Cauchemar, lorsqu'ils errent, choisissent parfois leur emplacement actuel comme nouvelle pièce préférée",
			"Les fantômes réduisent lentement la température de toute pièce dans laquelle ils se trouvent, y compris pendant les chasses",
			"Les événements fantômatique (apparition du fantôme, marche vers un joueur, boules de brouillard et souffles bruyants) réduisent la santé mentale de la cible de 10%. Tous les événements fantômatiques ciblent un seul joueur, et le fantôme peut se téléporter près d'un joueur pour effectuer un événement",
			"Pendant qu'un fantôme se manifeste (événement fantômatiques ou chasse), tous les joueurs sur la carte perdent 0,2% de santé mentale par seconde",
			"Tous les effets sonores de chasse et d'événements fantômatique diminuent avec la distance, jusqu'à 0% à 20m. Cela inclut la boîte à musique",
			"Les événements de boule de brouillard du fantôme ne téléportent pas le fantôme",
			"Les fantômes ne peuvent entendre les microphones des joueurs (et les appareils électroniques tenus) que dans un rayon de 8m sur le même étage",
			"Le fait de prononcer le nom d'un fantôme augmentera son niveau d'activité pendant un court laps de temps",
			"Un fantôme fera le même son d'ambiance pour chaque chasse; si le fantôme fait un son différent, il s'agit d'un événements fantômatique",
			"Les événements fantômatique éteignent la lumière dans la pièce du fantôme et ferment toutes les portes adjacentes (y compris les portes de sortie)",
			"Le disjoncteur sera toujours activé en difficulté Amateur et désactivé dans toutes les autres difficultés",
			"Jusqu'à 9 interrupteurs peuvent être allumés sur les petites cartes, 8 sur les moyennes et 7 sur les grandes cartes",
			"Si le disjoncteur est déclenché en allumant trop de lumières, toutes les lumières seront éteintes",
			"Tous les fantômes erreront occasionnellement en dehors de leur pièce : les petites errances sont courantes, les grandes errances sont rares.",
			"Le fantôme peut faire clignoter les lumières lorsqu'il est près d'un interrupteur.",
			"La santé mentale du joueur ne tombera pas en dessous de 50 % pendant la phase de préparation.",
			"Chaque membre de l'équipe perd 15 % de sa santé mentale par décès de joueur.",
		],
		gameplay_evidence:						"Informations évidentes",
		gameplay_evidence_items:			[
			"Les thermomètres se mettent à jour lentement ; soyez patients.",
			"Des températures glaciales correspondent à des températures inférieures à 0&deg;C ou 32&deg;F, ou si vous voyez de la vapeur d'haleine.",
			"Les valeurs EMF : 2 pour une interaction ; 3 pour un lancer ; 4 pour un événements fantômatique. 25% de chances de devenir 5 pour les fantômes EMF 5.",
			"Le tableau EMF du camion enregistre les valeurs EMF comme étant inférieures de 1 à leur valeur réelle, avec une variation optionnelle de +/-1 : EMF 3 peut s'afficher comme 1, 2 ou 3.",
			"Les spirit box fonctionneront n'importe où sur la carte, mais le fantôme n'écoutera que quelqu'un dans une pièce sans lumière, dans un rayon de 3m autour du fantôme.",
			"Les orbes fantômatiques n'apparaissent que dans la pièce préférée du fantôme et peuvent donc être utilisés pour suivre la localisation probable du fantôme.",
			"Les capteurs DOTS sont périodiquement activés par les fantômes dans un rayon de 7m et montrent des silhouettes en mouvement. Ils s'activent généralement toutes les 30s ou moins.",
			"Les caméras vidéo peuvent voir les orbes fantômatiques. Les orbes fantômatiques se déplacent autour de la pièce et se comportent comme des bulles.",
			"Les livres d'écriture fantômatique sont considérés par le fantôme comme des objets d'interaction standard et jetables, comme des objets aléatoires encombrants. Le fait d'enlever les objets encombrants peut augmenter les chances d'interaction du fantôme avec un livre.",
			"Une fois écrit, le livre d'écriture fantômatique se lévite et le stylo écrit - cela peut être observé via les caméras.",
			"Un fantôme avec la preuve &quot;Écritures fantômatiques&quot; écrira toujours dans le livre s'il le lance ; Si le livre a bougé et est vide, l'écriture peut être exclue.",
		],
		gameplay_non_evidence: 					"Informations moins évidentes",
		gameplay_non_evidence_items: [
			"Les caméras peuvent être utilisées pour prendre des photos des éléments suivants (par ordre de rentabilité) : fantômes, os, eau sale, crucifix usagés, objets maudits, livres écrits, silhouettes DOTS, empreintes digitales, pas, cadavres et interactions",
			"Les photos de fantômes ont toujours la priorité, et les interactions ont la priorité sur les empreintes digitales ; toutes les autres photos sont évaluées en fonction de la distance et de la distance par rapport au centre de l'image.",
			"Les opportunités de photo durent 20 secondes à partir de leur début. Plus on est proche, meilleure est la qualité et plus l'on gagne d'argent.",
			"Pour l'eau sale et l'écriture fantômatique, deux photos peuvent être prises : une pour l'eau sale et une autre pour l'événement d'interaction.",
			"Les capteurs sonores révèlent les noms de pièces dans le camion, et indiquent les interactions dans une zone.",
			"Le microphone a une portée de 40 m (vos oreilles entendent plus loin), mais peut détecter des interactions inaudibles.",
			"Les lampes UV et les bâtons lumineux illuminent les empreintes digitales et les pas (les empreintes digitales disparaissent après 2m). Les bâtons lumineux perdent en intensité après 1m.",
			"Les pas sont créés après que le fantôme ait marché dans le sel; placez-le dans les points de passage pour augmenter les chances.",
			"Les pilules de santé augmentent la santé individuelle de 40% (amateur), 35% (intermédiaire), 30% (pro), 25% (cauchemar). Elles ne peuvent pas être prises au-dessus de 95% de santé.",
			"Les bougies empêchent la perte passive de santé dans un rayon de 1m (tenue ou placée).",
			"Les crucifix empêchent les fantômes de chasser dans un rayon de 3m (tenue ou placée).",
			"Une fois qu'un crucifix a empêché une chasse, EMF 2 sera généré et le fantôme ne pourra pas tenter de chasser pendant 5s.",
			"Les bâtons d'encens empêchent les chasses de fantômes dans un rayon de 6m. Les effets durent 90s et bien que plusieurs puissent être utilisés, les minuteries d'encens ne peuvent pas être empilées. S'applique également pendant les chasses.",
			"Les bâtons d'encens utilisés pendant une chasse font oublier tous les joueurs au fantôme pendant 6s ; cet effet s'applique à tous les joueurs, même lorsqu'il est utilisé depuis l'extérieur de la zone de jeu.",
			"Les effets de répulsion des bâtons d'encens s'appliquent une fois par seconde pendant 6s, la durée de la combustion du bâton d'encens, mais ne s'additionne pas"
		],
		gameplay_cursed_items:	"Objets Maudits",
		gameplay_cursed_items_items: [
			"Toutes les cartes contiennent un objet maudit : une planche Ouija, des cartes de tarot, une poupée vaudou ou un miroir. Chaque objet n'a qu'un seul point d'apparition par carte.",
			"Les objets maudits déclenchent une chasse lorsque leur utilisation est terminée ou qu'ils sont cassés.",
			"Les chasses maudites ne peuvent pas être évitées, ont une période de grâce d'1 seconde, sont 20 secondes plus longues et les chasses ultérieures suivent la même règle.",
			"Les questions posées à la planche Ouija coûtent 5% de la santé mentale pour les questions sur l'âge et la durée de la mort, 20% pour les questions sur le nombre de personnes dans la pièce, et 50% pour les questions sur les os et l'emplacement du fantôme.",
			"L'emplacement du fantôme indiqué par la planche Ouija se réfère toujours à l'emplacement actuel du fantôme plutôt qu'à sa pièce préférée.",
			"Toujours dire au revoir à la planche Ouija avant de partir - ou être poursuivi !",
			"Réponses de la planche Ouija à la question « quelle est ma santé mentale » : Saine > 80% / Bonne > 60% / Moyenne > 40% / Mauvaise > 20% / Terrible < 20%.",
			"Réponses de la planche Ouija à la question « à quel point suis-je fou » : Pas très > 50% / Très > 25% / Fou : < 25%.",
			"Réponses de la planche Ouija à la question « suis-je fou » : Non > 90% / Peut-être > 20% / Oui < 20%.",
			"Le miroir montrera la pièce préférée du fantôme, mais drainera la santé mentale de 7,5%/s, avec un minimum de 20% par utilisation ; utiliser pendant ~2,5s draine autant de santé mentale qu'une utilisation de 1s.",
			"Les boîtes à musique attireront un fantôme proche et le feront chanter et essayer de trouver la boîte ; la santé mentale diminue lorsque la musique est audible.",
			"Si la boîte à musique est à moins de 5 m du fantôme pendant qu'elle joue, le fantôme apparaîtra, et une fois qu'il aura atteint la boîte ou après 5s, il tentera de chasser. Il est possible de quitter la zone avant que cela ne se produise pour éviter la chasse, bien que toutes les chasses ultérieures aient une durée de chasse maudite.",
			"L'utilisation d'une poupée vaudou fera effectuer une interaction ou donner des indices au fantôme, au prix de 5% de la santé mentale. L'épingle en forme de cœur déclenche une chasse pour 10% de santé mentale.",
			"Si l'utilisation d'une poupée vaudou ou d'un ouija consommerait plus de santé mentale que l'utilisateur n'en a, l'objet est consommé et une chasse maudite commence",
			"L'utilisation d'un cercle d'invocation coûte 16% de santé mentale par bougie allumée, déclenche un événement fantomatique et une chasse maudite subséquente",
			"Cartes de tarot: La Tour force une interaction ou une preuve / Le Diable force un événement fantomatique / La Mort force une chasse / La Fortune donne +/- 25% de santé mentale / Le Soleil donne 100% de santé mentale / La Lune prend 100% de santé mentale / L'Ermite renvoie le fantôme dans sa pièce / Le Pendu tue le joueur / La Prêtresse ranime un coéquipier mort ou enregistre une vie supplémentaire pour le groupe / Le Fou ne fait rien",
			"Les cartes de tarot deviennent toujours des cartes de Fou lorsqu'elles sont tirées pendant les chasses",
			"Allumer le cercle d'invocation pendant une chasse entraînera votre mort immédiate",
			"La Patte de Singe est toujours active lorsqu'elle est tenue ; faites attention à ne pas déclencher la reconnaissance vocale",
			"La Patte de Singe accorde des vœux en fonction du multiplicateur de difficulté : <2x = 5 vœux, <3x = 4 vœux, >3x = 3 vœux",
			"La perte de vision due à la Patte de Singe est importante et réduit la visibilité à 1 mètre ; il est recommandé de protéger les joueurs affectés",
			"La perte de vision et d'audition est supprimée à la mort et ne revient pas lors de la résurrection",
		],
		gameplay_monkey_paw:					"Souhaits de la Patte de Singe",
		gameplay_monkey_paw_items:		[
			"&quot;Je souhaite voir le fantôme&quot;: Toutes les portes externes se verrouillent, événement fantôme devant le joueur, après quoi une chasse commence. La vision du joueur est réduite pendant la durée de la chasse",
			"&quot;Je souhaite de l'activité&quot; / &quot;Je souhaite que le fantôme fasse quelque chose&quot;: Toute l'activité est doublée pendant 2 minutes, après quoi le disjoncteur saute et les portes externes se verrouillent pendant 2 minutes",
			"&quot;Je souhaite piéger le fantôme&quot; / &quot;Je souhaite que le fantôme soit piégé&quot;: Téléporte le fantôme dans sa salle préférée et verrouille les portes de la chambre du joueur et du fantôme pendant 1 minute. Le fantôme sera inactif pendant cette période, après quoi une chasse commencera. 25% de chances que les portes ne se déverrouillent qu'après la période de grâce",
			"&quot;Je souhaite être sain d'esprit&quot; / &quot;Je souhaite de la santé mentale&quot;: Tous les joueurs sont définis à 50% de santé mentale. La perte passive est définie à 1,5x, et la salle préférée du fantôme est aléatoire",
			"&quot;Je souhaite être en sécurité&quot;: Le lieu de cachette le plus proche est déverrouillé. Les lumières de la pièce se briseront et le fantôme pourra trouver le joueur pendant la durée de la manche",
			"&quot;Je souhaite partir&quot;: Toutes les portes externes sont déverrouillées en permanence, même pendant les chasses. La vitesse du joueur est ralentie, revenant lentement sur 5 secondes, avec une vision réduite",
			"&quot;Je souhaite ressusciter mon ami&quot; / &quot;Je souhaite la vie&quot;: Ressuscite le joueur mort, avec 50% de chances de tuer celui qui a fait le vœu",
			"&quot;Je souhaite avoir de la connaissance&quot;: Supprime 1 preuve incorrecte et les fantômes concernés du journal. Une chasse est initiée et le joueur ayant fait le vœu a une vue et une ouïe réduites pendant la durée de la manche",
			"&quot;Je souhaite du soleil / de la pluie / un ciel dégagé / du brouillard / de la neige / du vent&quot;: Les conditions météorologiques changent, aveuglant temporairement les joueurs. La santé mentale du joueur ayant fait le vœu est réduite de 25%. La pluie peut donner soit une pluie légère ou forte",
			"&quot;Je souhaite n'importe quoi&quot;: Accorde un vœu aléatoire inutilisé",
		],
		gameplay_hunts:	"Chasses",
		gameplay_hunts_items: [
			"Les chasses peuvent se produire une fois que la santé mentale moyenne du groupe est inférieure au seuil de santé mentale du fantôme (généralement 50%). La fréquence des tentatives de chasse dépend du fantôme individuel, cependant plus la santé mentale moyenne est basse, plus la chance de chasse est élevée",
			"Lorsqu'une chasse commence, toutes les portes extérieures sont verrouillées et les interrupteurs de lumière ne peuvent pas être utilisés",
			"Lorsqu'une chasse se termine, le fantôme se téléporte dans sa pièce préférée et toutes les lumières s'éteignent",
			"La vitesse d'un fantôme peut être déterminée en écoutant ses pas ; les fantômes plus lents marchent beaucoup moins souvent",
			"Périodes de grâce : Amateur : 5s, Intermédiaire : 4s, Professionnel : 3s, Cauchemar : 2s. Chasses maudites : 1s",
			"Une fois une chasse terminée, il y a un temps de recharge de 25s après lequel une autre chasse peut être tentée",
			"En mode Cauchemar, si un joueur meurt pendant une chasse, la durée de la chasse sera prolongée de 12s",
			"Les fantômes se déplacent à la vitesse de base du joueur, qui augmente rapidement lorsqu'ils poursuivent un joueur, jusqu'à 150%. Lorsque la ligne de vue est perdue, le fantôme maintient la vitesse actuelle jusqu'à ce qu'il atteigne le dernier point de la ligne de vue, après quoi il réduit lentement sa vitesse de retour à la vitesse de base. Cela ne s'applique pas au Revenant ou au Deogen",
			"Les fantômes ont 50% de chance de lancer un objet dans leur portée toutes les 0,5s",
			"Les fantômes perturbent l'électronique dans un rayon de 10m",
			"Les fantômes ne peuvent entendre que les microphones des joueurs - les autres sons n'attirent pas le fantôme",
			"Les fantômes peuvent détecter les appareils électroniques tenus par les joueurs sous tension (y compris les lampes de poche, mais pas les caméras frontales) dans leur plage d'écoute ; éteignez-les ou basculez-les pour éviter d'être détecté",
			"Les portes bloquent la ligne de vue ; les fermer derrière vous peut empêcher le fantôme de gagner de la vitesse",
			"Les joueurs peuvent se cacher derrière des portes de placard et de vestiaire tout en les maintenant - les fantômes peuvent déplacer toutes les portes non maintenues, exposant ainsi les joueurs cachés. Les fantômes ouvriront toutefois de force les portes de pièce maintenues pour exposer les joueurs",
			"Si un fantôme voit un joueur entrer dans un placard ou un vestiaire, il essaiera de les ouvrir, même si les portes sont maintenues. Continuez à les fermer pour survivre",
			"Faire du bruit ou activer des appareils électroniques à l'intérieur d'un casier ou d'une armoire forcera le fantôme à ouvrir les portes ; cela est rarement survivable.",
			"Les bâtons d'encens peuvent être utilisés dans un rayon de 6 mètres d'un fantôme pour le faire errer au hasard et oublier toutes les cibles pendant 6 secondes.",
			"Les bâtons d'encens peuvent également être utilisés par un joueur non poursuivi, même dans le camion, si le fantôme poursuit un autre joueur.",
		],
		gameplay_nerd_info:	"Infos pour les geeks",
		gameplay_nerd_info_items: [
			"La vitesse de base du joueur est de 1,6 m/s ; en courant, elle est de 3 m/s",
			"Intervalle de température pour la vitesse de chasse exact pour le fantôme Hantu : 1,4 m/s à 15°C / 1,75 m/s à 12°C / 2,1 m/s à 9°C / 2,3 m/s à 6°C / 2,5 m/s à 3°C / 2,7 m/s à 0°C",
			"Vitesse exacte de chasse pour le Revenant : 1 m/s quand il ne poursuit pas un joueur et 3 m/s quand il en poursuit un",
			"La santé mentale diminue de manière passive dans les zones non éclairées (même les zones sombres dans les pièces éclairées) à 0,12 % par seconde sur les petites cartes, 0,08 % sur les cartes moyennes, 0,05 % sur les grandes cartes",
			"Pendant la phase de configuration, la diminution passive de la santé mentale est réduite : 0,09 % sur les petites cartes, 0,05 % sur les cartes moyennes, 0,03 % sur les grandes cartes",
			"La diminution passive de la santé mentale est multipliée selon la difficulté : Intermediate est de 1,5x, Professional est de 2x",
			"Si vous jouez en solo, toutes les diminutions passives de santé mentale sont réduites de moitié",
		],
	},
};
